import IMG from "./th.png";

export const PROJECTS = [
  {
    name: "Spaceship wars",
    img: IMG,
    description:
      "An interactive web application designed to enhance user experience through responsive design and intuitive navigation. Built with modern frontend technologies, this project highlights clean code, creative problem-solving, and optimized performance.",
  },
  {
    name: "Spaceship wars",
    img: IMG,
    description:
      "An interactive web application designed to enhance user experience through responsive design and intuitive navigation. Built with modern frontend technologies, this project highlights clean code, creative problem-solving, and optimized performance.",
  },
  {
    name: "Spaceship wars",
    img: IMG,
    description:
      "An interactive web application designed to enhance user experience through responsive design and intuitive navigation. Built with modern frontend technologies, this project highlights clean code, creative problem-solving, and optimized performance.",
  },
  {
    name: "Spaceship wars",
    img: IMG,
    description:
      "An interactive web application designed to enhance user experience through responsive design and intuitive navigation. Built with modern frontend technologies, this project highlights clean code, creative problem-solving, and optimized performance.",
  },
  {
    name: "Spaceship wars",
    img: IMG,
    description:
      "An interactive web application designed to enhance user experience through responsive design and intuitive navigation. Built with modern frontend technologies, this project highlights clean code, creative problem-solving, and optimized performance.",
  },
];
